# -*- coding: utf-8 -*-
"""HieuDT_DoAn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12b54tJC0AY25EQjjChsi7uwJhAKnb2ZZ
"""

# !pip install ultralytics
# !pip install fastapi uvicorn pyngrok nest_asyncio
# !pip install opencv-python-headless requests
# !pip install ultralytics
# !pip install fastapi uvicorn pyngrok nest_asyncio
# !pip install opencv-python-headless requests
# !pip install fastdtw scipy
# !pip install google-generativeai
# !pip install -q ultralytics fastapi uvicorn pyngrok fastdtw nest-asyncio google-genai

# # Cài zstd
# !sudo apt-get install -y zstd

# # Cài Ollama
# !curl -fsSL https://ollama.com/install.sh | sh

import subprocess, threading, time

def run_ollama():
    subprocess.run(["ollama", "serve"],
                   stdout=subprocess.DEVNULL,
                   stderr=subprocess.DEVNULL)

threading.Thread(target=run_ollama, daemon=True).start()
time.sleep(5)
print("✅ Ollama server started at localhost:11434")

# !ollama pull qwen2.5:3b

from ultralytics import YOLO

model = YOLO("yolov8n-pose.pt")

print("YOLO Pose OK")

# =========================================================
# AI POSE ANALYSIS API - OPTIMIZED VERSION v2.3
# =========================================================

# =========================================================
# IMPORT
# =========================================================

import os
import cv2
import json
import uuid
import asyncio
import requests
import numpy as np
import nest_asyncio
import re
from concurrent.futures import ThreadPoolExecutor

from ultralytics import YOLO
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Dict, Any
from pyngrok import ngrok
import uvicorn
from fastdtw import fastdtw

# =========================================================
# FIX ASYNC CHO COLAB
# =========================================================

nest_asyncio.apply()

# =========================================================
# KILL TUNNEL CŨ
# =========================================================

ngrok.kill()

# =========================================================
# THREAD POOL
# =========================================================

executor = ThreadPoolExecutor(max_workers=4)

# =========================================================
# FASTAPI
# =========================================================

app = FastAPI(title="AI Pose Analysis API", version="2.3.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =========================================================
# LOAD YOLO POSE
# =========================================================

model = YOLO("yolov8n-pose.pt")

try:
    model.to("cuda")
    print("✅ Using GPU")
except:
    print("⚠️ Using CPU")

print("✅ YOLO Pose Loaded")

# =========================================================
# OLLAMA CONFIG
# =========================================================

OLLAMA_URL   = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5:3b"
print(f"✅ Using Local AI: {OLLAMA_MODEL}")

# =========================================================
# DANH SÁCH 8 GÓC PHÂN TÍCH
# =========================================================
#
#  YOLO Pose Keypoints:
#   5  = Vai trái        6  = Vai phải
#   7  = Khuỷu tay trái  8  = Khuỷu tay phải
#   9  = Cổ tay trái     10 = Cổ tay phải
#   11 = Hông trái       12 = Hông phải
#   13 = Đầu gối trái    14 = Đầu gối phải
#   15 = Mắt cá trái     16 = Mắt cá phải
#
#  Góc tính tại điểm GIỮA của 3 điểm (A → B ← C):
#   left_shoulder  : Hông T[11] → Vai T[5]  ← Khuỷu T[7]
#   right_shoulder : Hông P[12] → Vai P[6]  ← Khuỷu P[8]
#   left_elbow     : Vai T[5]   → Khuỷu T[7] ← Cổ tay T[9]
#   right_elbow    : Vai P[6]   → Khuỷu P[8] ← Cổ tay P[10]
#   left_hip       : Vai T[5]   → Hông T[11] ← Gối T[13]
#   right_hip      : Vai P[6]   → Hông P[12] ← Gối P[14]
#   left_knee      : Hông T[11] → Gối T[13]  ← Mắt cá T[15]
#   right_knee     : Hông P[12] → Gối P[14]  ← Mắt cá P[16]
#
# =========================================================

ANGLE_KEYS = [
    "left_shoulder", "right_shoulder",
    "left_elbow",    "right_elbow",
    "left_hip",      "right_hip",
    "left_knee",     "right_knee",
]

ANGLE_LABELS_VI = {
    "left_shoulder":  "Vai trái",
    "right_shoulder": "Vai phải",
    "left_elbow":     "Khuỷu tay trái",
    "right_elbow":    "Khuỷu tay phải",
    "left_hip":       "Hông trái",
    "right_hip":      "Hông phải",
    "left_knee":      "Đầu gối trái",
    "right_knee":     "Đầu gối phải",
}

# =========================================================
# DTO
# =========================================================

class ExtractTemplateRequest(BaseModel):
    videoUrl: str

class ExtractStudentRequest(BaseModel):
    videoUrl: str

class ComparePoseRequest(BaseModel):
    standardData: Dict[str, Any]
    studentData:  Dict[str, Any]

class EvaluateRequest(BaseModel):
    standardData: Dict[str, Any]
    studentData:  Dict[str, Any]
    scores:       Dict[str, float]

# =========================================================
# DOWNLOAD VIDEO
# =========================================================

def download_video(video_url: str) -> str:
    file_name = f"{uuid.uuid4()}.mp4"
    response  = requests.get(video_url, stream=True, timeout=30)
    if response.status_code != 200:
        raise Exception("Không tải được video")
    with open(file_name, "wb") as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)
    return file_name

# =========================================================
# CALCULATE ANGLE
# =========================================================

def calculate_angle(a, b, c) -> float:
    """
    Tính góc tại điểm B tạo bởi 3 điểm A-B-C.
    Kết quả trong khoảng [0°, 180°].
    """
    a = np.array(a)
    b = np.array(b)
    c = np.array(c)
    radians = (
        np.arctan2(c[1] - b[1], c[0] - b[0]) -
        np.arctan2(a[1] - b[1], a[0] - b[0])
    )
    angle = np.abs(radians * 180.0 / np.pi)
    if angle > 180:
        angle = 360 - angle
    return round(float(angle), 2)

# =========================================================
# EXTRACT POSE DATA
# =========================================================

def extract_pose_data(video_url: str) -> dict:
    local_path  = download_video(video_url)
    cap         = cv2.VideoCapture(local_path)

    if not cap.isOpened():
        raise Exception("Không mở được video")

    fps         = cap.get(cv2.CAP_PROP_FPS) or 30.0
    sample_rate = max(1, int(fps / 5))   # lấy mẫu ~5 frame/giây
    frames_data = []
    frame_index = 0

    # Tất cả keypoints từ vai → mắt cá (bỏ mặt)
    IMPORTANT_POINTS = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

    while cap.isOpened():
        success, frame = cap.read()
        if not success:
            break

        if frame_index % sample_rate != 0:
            frame_index += 1
            continue

        try:
            results = model(frame, imgsz=640, verbose=False)
            kp      = results[0].keypoints

            if kp is None or kp.xy.shape[0] == 0 or kp.conf is None:
                frame_index += 1
                continue

            keypoints  = kp.xy[0].cpu().numpy()
            confidence = kp.conf[0].cpu().numpy()

            # Bỏ frame nếu bất kỳ keypoint quan trọng nào < 50% confidence
            if not all(confidence[i] >= 0.5 for i in IMPORTANT_POINTS):
                frame_index += 1
                continue

            frames_data.append({
                "frame_index": int(frame_index),
                "timestamp":   round(frame_index / fps, 2),
                "angles": {
                    # ── Vai ──────────────────────────────────────────────
                    "left_shoulder":  calculate_angle(keypoints[11], keypoints[5],  keypoints[7]),
                    "right_shoulder": calculate_angle(keypoints[12], keypoints[6],  keypoints[8]),
                    # ── Khuỷu tay ────────────────────────────────────────
                    "left_elbow":     calculate_angle(keypoints[5],  keypoints[7],  keypoints[9]),
                    "right_elbow":    calculate_angle(keypoints[6],  keypoints[8],  keypoints[10]),
                    # ── Hông ─────────────────────────────────────────────
                    "left_hip":       calculate_angle(keypoints[5],  keypoints[11], keypoints[13]),
                    "right_hip":      calculate_angle(keypoints[6],  keypoints[12], keypoints[14]),
                    # ── Đầu gối ──────────────────────────────────────────
                    "left_knee":      calculate_angle(keypoints[11], keypoints[13], keypoints[15]),
                    "right_knee":     calculate_angle(keypoints[12], keypoints[14], keypoints[16]),
                }
            })

        except Exception as e:
            print(f"⚠️ Frame {frame_index} Error: {e}")

        frame_index += 1

    cap.release()

    if os.path.exists(local_path):
        os.remove(local_path)

    return {"total_frames": len(frames_data), "frames": frames_data}

# =========================================================
# DTW SCORING
# =========================================================

def extract_angle_sequence(data: dict, angle_key: str) -> list:
    return [f["angles"][angle_key] for f in data.get("frames", [])]

def calculate_dtw_score(std_seq: list, stu_seq: list) -> float:
    """
    So sánh 2 chuỗi góc bằng Dynamic Time Warping.
    - Lệch 0°  → 100 điểm
    - Lệch 45° → 0 điểm
    """
    if not std_seq or not stu_seq:
        return 0.0
    distance, path = fastdtw(std_seq, stu_seq, dist=lambda x, y: abs(x - y))
    avg_distance   = distance / len(path) if path else 180.0
    score          = 100.0 * (1.0 - (avg_distance / 45.0))
    return max(0.0, min(100.0, round(score, 2)))

# =========================================================
# EVALUATE HELPERS
# =========================================================

def build_chart_data(standard_data: dict, student_data: dict) -> dict:
    """Tạo dữ liệu biểu đồ cho cả 8 góc."""
    charts     = {}
    std_frames = standard_data.get("frames", [])
    stu_frames = student_data.get("frames",  [])

    for key in ANGLE_KEYS:
        charts[key] = {
            "label": ANGLE_LABELS_VI[key],
            "standard": {
                "labels": [f["timestamp"]   for f in std_frames],
                "values": [f["angles"][key] for f in std_frames]
            },
            "student": {
                "labels": [f["timestamp"]   for f in stu_frames],
                "values": [f["angles"][key] for f in stu_frames]
            }
        }

    return charts

def get_rating(score: float) -> str:
    if   score >= 90: return "Xuất sắc"
    elif score >= 75: return "Khá"
    elif score >= 60: return "Trung bình"
    else:             return "Cần cải thiện"

# =========================================================
# LOCAL AI (OLLAMA) COMMENT
# =========================================================

def generate_ai_comment(scores: dict) -> dict:
    """
    Gọi Ollama local (qwen2.5:3b) để sinh nhận xét chuyên sâu
    dựa trên điểm số của 8 góc khớp.
    """

    # Xây dựng phần điểm chi tiết
    score_lines = "\n".join(
        f"- {ANGLE_LABELS_VI[key]:<20}: {scores.get(key, 0):.1f}/100"
        for key in ANGLE_KEYS
    )

    # Liệt kê các khớp yếu (< 80 điểm) để AI tập trung phân tích
    weak_joints = [
        f"{ANGLE_LABELS_VI[k]} ({scores.get(k, 0):.1f}/100)"
        for k in ANGLE_KEYS if scores.get(k, 0) < 80
    ]
    weak_text = ", ".join(weak_joints) if weak_joints else "Không có khớp yếu"

    prompt = (
        "Bạn là giảng viên thể dục quốc phòng tại trường đại học Việt Nam. "
        "Nhiệm vụ của bạn là đánh giá tư thế thực hiện động tác quốc phòng của sinh viên "
        "dựa trên phân tích góc độ 8 khớp cơ thể được đo bằng AI.\n\n"

        "=== KẾT QUẢ PHÂN TÍCH TƯ THẾ (thang 100) ===\n"
        f"{score_lines}\n"
        f"- {'Tổng điểm':<20}: {scores.get('overall', 0):.1f}/100\n\n"

        f"=== CÁC KHỚP CẦN CẢI THIỆN (< 80 điểm) ===\n"
        f"{weak_text}\n\n"

        "=== HƯỚNG DẪN ĐÁNH GIÁ ===\n"
        "Với mỗi khớp có điểm DƯỚI 80, hãy phân tích:\n"
        "1. Lỗi tư thế thường gặp trong các động tác quốc phòng tại khớp đó\n"
        "   (ví dụ: vai không thẳng khi đứng nghiêm, hông lệch khi quay đều,\n"
        "    gối không đúng góc khi bước đều...)\n"
        "2. Cách khắc phục theo đúng điều lệnh quân sự\n"
        "3. Bài tập cụ thể để cải thiện khớp đó\n\n"

        "Với các khớp có điểm TỪ 80 TRỞ LÊN, hãy ghi nhận điểm mạnh.\n\n"

        "Chỉ trả về JSON thuần (không markdown, không giải thích thêm):\n"
        '{'
        '"comment": "Nhận xét tổng quan về phong cách thực hiện động tác",'
        '"strengths": ["Điểm mạnh 1", "Điểm mạnh 2"],'
        '"suggestions": ['
        '  {"joint": "Tên khớp", "score": 0, "issue": "Mô tả lỗi", "fix": "Cách khắc phục", "exercise": "Bài tập"}'
        '],'
        '"priority": "Khớp quan trọng nhất cần tập trung cải thiện trước"'
        '}'
    )

    try:
        print(f"🚀 Calling Ollama ({OLLAMA_MODEL})...")
        response = requests.post(
            OLLAMA_URL,
            json={
                "model":  OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "format": "json",
                "options": {
                    "temperature": 0.3,
                    "num_predict": 800   # tăng lên để đủ chỗ cho 8 khớp
                }
            },
            timeout=180
        )
        raw = response.json().get("response", "")
        print(f"📩 Ollama raw:\n{raw[:400]}")

        json_match = re.search(r'\{[\s\S]*\}', raw)
        if not json_match:
            raise ValueError("Không tìm thấy JSON trong response")

        parsed = json.loads(json_match.group())
        print("✅ Ollama parsed OK")
        return parsed

    except Exception as e:
        print(f"❌ Ollama FAILED [{type(e).__name__}]: {e}")

        # Fallback: tự tạo nhận xét đơn giản dựa trên điểm
        overall = scores.get("overall", 0)
        auto_suggestions = [
            {
                "joint":    ANGLE_LABELS_VI[k],
                "score":    scores.get(k, 0),
                "issue":    "Góc khớp chưa đạt chuẩn so với mẫu",
                "fix":      "Quan sát lại video mẫu và điều chỉnh tư thế",
                "exercise": "Tập luyện lặp lại động tác chậm trước gương"
            }
            for k in ANGLE_KEYS if scores.get(k, 0) < 80
        ]
        auto_strengths = [
            f"{ANGLE_LABELS_VI[k]} đạt {scores.get(k, 0):.0f}/100"
            for k in ANGLE_KEYS if scores.get(k, 0) >= 80
        ]

        return {
            "comment":     f"Tổng điểm đạt {overall:.1f}/100. {'Thực hiện tốt, tiếp tục duy trì.' if overall >= 80 else 'Cần tập luyện thêm để cải thiện tư thế.'}",
            "suggestions": auto_suggestions,
            "strengths":   auto_strengths if auto_strengths else ["Đã hoàn thành bài kiểm tra."],
            "priority":    min(
                (k for k in ANGLE_KEYS if scores.get(k, 0) < 80),
                key=lambda k: scores.get(k, 100),
                default=""
            )
        }

# =========================================================
# ROUTES
# =========================================================

@app.get("/")
async def root():
    return {
        "status":  "running",
        "version": "2.3.0",
        "ai":      OLLAMA_MODEL,
        "message": "AI Pose API Running",
        "angles":  ANGLE_KEYS
    }

# ----------------------------------------------------------

@app.post("/api/ai/extract-template")
async def extract_template(request: ExtractTemplateRequest):
    try:
        loop = asyncio.get_event_loop()
        data = await loop.run_in_executor(executor, extract_pose_data, request.videoUrl)
        return {
            "status":       "success",
            "message":      "Extract template successfully",
            "standardData": data
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ----------------------------------------------------------

@app.post("/api/ai/extract-student")
async def extract_student(request: ExtractStudentRequest):
    try:
        loop = asyncio.get_event_loop()
        data = await loop.run_in_executor(executor, extract_pose_data, request.videoUrl)
        return {
            "status":      "success",
            "message":     "Extract student successfully",
            "studentData": data
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ----------------------------------------------------------

@app.post("/api/ai/compare-pose")
async def compare_pose(request: ComparePoseRequest):
    """
    So sánh DTW cho cả 8 góc khớp.
    Điểm overall = trung bình cộng 8 góc.
    """
    try:
        std, stu = request.standardData, request.studentData

        scores = {
            key: calculate_dtw_score(
                extract_angle_sequence(std, key),
                extract_angle_sequence(stu, key)
            )
            for key in ANGLE_KEYS
        }

        scores["overall"] = round(sum(scores.values()) / len(ANGLE_KEYS), 2)

        return {
            "status":  "success",
            "message": "Comparison completed",
            "scores":  scores
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ----------------------------------------------------------

@app.post("/api/ai/evaluate")
async def evaluate(request: EvaluateRequest):
    """
    Tạo biểu đồ 8 góc + AI nhận xét chi tiết song song.
    """
    try:
        loop = asyncio.get_event_loop()

        charts_task  = loop.run_in_executor(
            executor, build_chart_data, request.standardData, request.studentData
        )
        comment_task = loop.run_in_executor(
            executor, generate_ai_comment, request.scores
        )

        charts, ai_result = await asyncio.gather(charts_task, comment_task)

        return {
            "status":  "success",
            "message": "Evaluation completed successfully",
            "evaluation": {
                "rating":      get_rating(request.scores.get("overall", 0)),
                "comment":     ai_result.get("comment",     "Chưa có nhận xét."),
                "suggestions": ai_result.get("suggestions", []) if isinstance(ai_result.get("suggestions"), list) else [],
                "strengths":   ai_result.get("strengths",   []) if isinstance(ai_result.get("strengths"),   list) else [],
                "priority":    ai_result.get("priority",    ""),
            },
            "scores": request.scores,
            "charts": charts
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/ping")
async def health_check():
    return {"status": "healthy"}


# =========================================================
# RUN
# =========================================================

if __name__ == "__main__":
    config = uvicorn.Config(app=app, host="0.0.0.0", port=8000, log_level="info")
    server = uvicorn.Server(config)
    server.run()